using System;
using System.Collections.Generic;
using EmberTern.App.ViewModels;
using EmberTern.Core.Metadata;
using Xunit;

namespace EmberTern.Tests;

public class AddFieldDialogVmTests
{
    private static AddFieldDialogViewModel Make(string table = "T")
        => new(table, Array.Empty<DomainSpec>(), Array.Empty<string>());

    [Fact]
    public void IsValid_FailsOnEmptyName()
    {
        var vm = Make();
        Assert.False(vm.IsValid());
        Assert.NotEmpty(vm.ValidationMessage);
    }

    // #4 — a computed expression disables the Domain / Basic-type / Default /
    // Autoincrement controls (mutually exclusive with COMPUTED BY).
    [Fact]
    public void HasComputed_GatesTypeSections()
    {
        var vm = Make();
        Assert.True(vm.IsRegularTypeEnabled);
        vm.ComputedExpression = "A + B";
        Assert.True(vm.HasComputed);
        Assert.False(vm.IsRegularTypeEnabled);
        Assert.False(vm.IsAutoincTabEnabled);
        vm.ComputedExpression = "";
        Assert.True(vm.IsRegularTypeEnabled);
    }

    // #5 — ClearDomain resets the selected domain; CanExecute tracks selection.
    [Fact]
    public void ClearDomain_ResetsSelectedDomain()
    {
        var vm = new AddFieldDialogViewModel("T",
            new[] { new DomainSpec("T_KWOTA", "NUMERIC(15,2)") },
            Array.Empty<string>());
        Assert.False(vm.ClearDomainCommand.CanExecute(null));
        vm.SelectedDomain = vm.Domains[0];
        Assert.True(vm.ClearDomainCommand.CanExecute(null));

        vm.ClearDomainCommand.Execute(null);

        Assert.Null(vm.SelectedDomain);
        Assert.True(vm.IsDomainEmpty);
        Assert.False(vm.ClearDomainCommand.CanExecute(null));
    }

    [Fact]
    public void IsValid_PassesOnNonEmptyName()
    {
        var vm = Make();
        vm.FieldName = "AGE";
        Assert.True(vm.IsValid());
        Assert.Empty(vm.ValidationMessage);
    }

    [Fact]
    public void DdlPreview_LiveUpdates_OnFieldNameChange()
    {
        var vm = Make("PERSON");
        Assert.Contains("<field>", vm.DdlPreview);

        vm.FieldName = "AGE";
        Assert.Contains("\"AGE\"", vm.DdlPreview);
        Assert.DoesNotContain("<field>", vm.DdlPreview);
    }

    [Fact]
    public void DdlPreview_VarcharSizeAppears()
    {
        var vm = Make();
        vm.FieldName = "NAZWA";
        vm.SelectedBasicType = "VARCHAR";
        vm.Size = 80;
        Assert.Contains("VARCHAR(80)", vm.DdlPreview);
    }

    [Fact]
    public void DdlPreview_NumericPrecisionScale_BothAppear()
    {
        var vm = Make();
        vm.FieldName = "CENA";
        vm.SelectedBasicType = "NUMERIC";
        vm.Precision = 15;
        vm.Scale = 2;
        Assert.Contains("NUMERIC(15,2)", vm.DdlPreview);
    }

    [Fact]
    public void DdlPreview_NotNullAndPrimaryKey_BothEmitted()
    {
        var vm = Make();
        vm.FieldName = "ID";
        vm.SelectedBasicType = "INTEGER";
        vm.NotNull = true;
        vm.PrimaryKey = true;
        Assert.Contains("NOT NULL", vm.DdlPreview);
        Assert.Contains("PRIMARY KEY", vm.DdlPreview);
    }

    [Fact]
    public void DdlPreview_DomainOverridesBasicType()
    {
        var vm = Make();
        vm.FieldName = "ID_KRAJ";
        vm.SelectedBasicType = "VARCHAR";
        vm.SelectedDomain = new DomainSpec("T_ID", "INTEGER");
        // Generated-DDL identifier style: the domain shows UPPERCASE + bare (not quoted).
        Assert.Contains("T_ID", vm.DdlPreview);
        Assert.DoesNotContain("\"T_ID\"", vm.DdlPreview);
        Assert.DoesNotContain("VARCHAR", vm.DdlPreview);
    }

    [Fact]
    public void DdlPreview_ComputedExpression_TakesPriority()
    {
        var vm = Make();
        vm.FieldName = "WARTOSC";
        vm.ComputedExpression = "ILOSC * CENA";
        Assert.Contains("COMPUTED BY (ILOSC * CENA)", vm.DdlPreview);
    }

    [Fact]
    public void DdlPreview_CheckExpressionAppendsClause()
    {
        var vm = Make();
        vm.FieldName = "RABAT";
        vm.SelectedBasicType = "NUMERIC";
        vm.Precision = 5;
        vm.Scale = 2;
        vm.CheckExpression = "VALUE >= 0";
        Assert.Contains("CHECK (VALUE >= 0)", vm.DdlPreview);
    }

    [Fact]
    public void DdlPreview_DefaultValueLiteral_AppearsAfterType()
    {
        var vm = Make();
        vm.FieldName = "FLAGA";
        vm.SelectedBasicType = "SMALLINT";
        vm.DefaultValue = "0";
        Assert.Contains("DEFAULT 0", vm.DdlPreview);
    }

    [Fact]
    public void DdlPreview_IdentityAutoincEmitsClause()
    {
        var vm = Make();
        vm.FieldName = "ID";
        vm.SelectedBasicType = "INTEGER";
        vm.NotNull = true;
        vm.IsAutoincIdentity = true;
        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", vm.DdlPreview);
    }

    [Fact]
    public void DdlPreview_NewGenerator_PrintsGeneratorAndTriggerStatements()
    {
        var vm = Make("NAGL");
        vm.FieldName = "ID";
        vm.SelectedBasicType = "INTEGER";
        vm.NotNull = true;
        vm.IsAutoincNew = true;
        vm.NewGeneratorName = "GEN_NAGL_ID";
        Assert.Contains("CREATE GENERATOR \"GEN_NAGL_ID\"", vm.DdlPreview);
        Assert.Contains("CREATE TRIGGER", vm.DdlPreview);
    }

    [Fact]
    public void IsAutoincRadioButtons_ExclusiveSelection()
    {
        var vm = Make();
        Assert.True(vm.IsAutoincNone);

        vm.IsAutoincIdentity = true;
        Assert.True(vm.IsAutoincIdentity);
        Assert.False(vm.IsAutoincNone);
        Assert.False(vm.IsAutoincExisting);

        vm.IsAutoincNew = true;
        Assert.True(vm.IsAutoincNew);
        Assert.False(vm.IsAutoincIdentity);
    }

    [Fact]
    public void BuildDefinition_TrimsName()
    {
        var vm = Make();
        vm.FieldName = "  AGE  ";
        vm.SelectedBasicType = "INTEGER";
        Assert.True(vm.IsValid());
        var def = vm.BuildDefinition();
        Assert.Equal("AGE", def.Name);
    }

    [Fact]
    public void BuildDefinition_NewGeneratorMode_FillsGeneratorName()
    {
        var vm = Make();
        vm.FieldName = "ID";
        vm.IsAutoincNew = true;
        vm.NewGeneratorName = "MY_GEN";
        var def = vm.BuildDefinition();
        Assert.Equal(AutoIncrementMode.NewGenerator, def.AutoIncrement);
        Assert.Equal("MY_GEN", def.GeneratorName);
    }

    [Fact]
    public void AcceptCommand_FillsResultAndFiresClose()
    {
        var vm = Make();
        vm.FieldName = "AGE";
        var closed = false;
        vm.RequestClose += () => closed = true;
        vm.AcceptCommand.Execute(null);
        Assert.NotNull(vm.Result);
        Assert.True(closed);
    }

    [Fact]
    public void AcceptCommand_DoesNothingWhenInvalid()
    {
        var vm = Make();
        vm.AcceptCommand.Execute(null);
        Assert.Null(vm.Result);
    }

    [Fact]
    public void CancelCommand_LeavesResultNullAndFiresClose()
    {
        var vm = Make();
        vm.FieldName = "AGE";
        var closed = false;
        vm.RequestClose += () => closed = true;
        vm.CancelCommand.Execute(null);
        Assert.Null(vm.Result);
        Assert.True(closed);
    }

    [Fact]
    public void Domains_PopulatedFromConstructor()
    {
        var specs = new[]
        {
            new DomainSpec("T_ID", "INTEGER"),
            new DomainSpec("T_KWOTA", "NUMERIC(15,2)"),
        };
        var vm = new AddFieldDialogViewModel("T", specs, System.Array.Empty<string>());
        Assert.Equal(2, vm.Domains.Count);
        Assert.Equal("T_KWOTA", vm.Domains[1].Name);
        Assert.Equal("NUMERIC(15,2)", vm.Domains[1].Type);
    }

    [Fact]
    public void BuildDefinition_DomainNameOnly_NotFormatted()
    {
        var vm = Make();
        vm.FieldName = "ID_KRAJ";
        vm.SelectedDomain = new DomainSpec("T_ID", "INTEGER");
        var def = vm.BuildDefinition();
        Assert.Equal("T_ID", def.Domain);
    }
}
