using EmberTern.Core.Metadata;
using EmberTern.Firebird;
using Xunit;

namespace EmberTern.Tests;

public class CreateTableDdlTests
{
    private static TableSpec MakeSpec(TableKind kind = TableKind.Persistent)
    {
        var spec = new TableSpec { Kind = kind };
        spec.Fields.Add(new FieldDefinition
        {
            Name = "ID",
            BasicType = "INTEGER",
            NotNull = true,
            PrimaryKey = true,
        });
        spec.Fields.Add(new FieldDefinition
        {
            Name = "NAZWA",
            BasicType = "VARCHAR",
            Size = 100,
        });
        return spec;
    }

    [Fact]
    public void Persistent_EmitsPlainCreateTable()
    {
        var sql = DdlGenerator.BuildCreateTable("ADRES", MakeSpec());
        Assert.StartsWith("CREATE TABLE \"ADRES\"", sql);
        Assert.DoesNotContain("GLOBAL TEMPORARY", sql);
        Assert.DoesNotContain("ON COMMIT", sql);
    }

    [Fact]
    public void TempDelete_EmitsGlobalTemporary_OnCommitDeleteRows()
    {
        var sql = DdlGenerator.BuildCreateTable("TMP", MakeSpec(TableKind.TempDeleteRows));
        Assert.Contains("CREATE GLOBAL TEMPORARY TABLE \"TMP\"", sql);
        Assert.Contains("ON COMMIT DELETE ROWS", sql);
    }

    [Fact]
    public void TempPreserve_EmitsGlobalTemporary_OnCommitPreserveRows()
    {
        var sql = DdlGenerator.BuildCreateTable("TMP", MakeSpec(TableKind.TempPreserveRows));
        Assert.Contains("CREATE GLOBAL TEMPORARY TABLE \"TMP\"", sql);
        Assert.Contains("ON COMMIT PRESERVE ROWS", sql);
    }

    [Fact]
    public void Persistent_EmitsNamedPrimaryKeyConstraint()
    {
        var sql = DdlGenerator.BuildCreateTable("ADRES", MakeSpec());
        Assert.Contains("CONSTRAINT \"PK_ADRES\" PRIMARY KEY (\"ID\")", sql);
    }

    [Fact]
    public void FieldsRenderInOrder_WithCommas()
    {
        var sql = DdlGenerator.BuildCreateTable("T", MakeSpec());
        var idIdx = sql.IndexOf("\"ID\"", System.StringComparison.Ordinal);
        var nazwaIdx = sql.IndexOf("\"NAZWA\"", System.StringComparison.Ordinal);
        Assert.True(idIdx > 0 && nazwaIdx > idIdx, "ID must come before NAZWA");
        Assert.Contains("VARCHAR(100)", sql);
    }

    [Fact]
    public void Identity_InlineGeneratedByDefault()
    {
        var spec = new TableSpec();
        spec.Fields.Add(new FieldDefinition
        {
            Name = "ID", BasicType = "INTEGER", NotNull = true, PrimaryKey = true,
            AutoIncrement = AutoIncrementMode.Identity,
        });
        var sql = DdlGenerator.BuildCreateTable("T", spec);
        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", sql);
        Assert.DoesNotContain("CREATE SEQUENCE", sql);
        Assert.DoesNotContain("CREATE TRIGGER", sql);
    }

    [Fact]
    public void NewGenerator_EmitsSequenceAndTriggerAfterCreate()
    {
        var spec = new TableSpec();
        spec.Fields.Add(new FieldDefinition
        {
            Name = "ID", BasicType = "INTEGER",
            AutoIncrement = AutoIncrementMode.NewGenerator,
        });
        var sql = DdlGenerator.BuildCreateTable("ORDERS", spec);
        Assert.Contains("CREATE SEQUENCE \"GEN_ORDERS_ID\"", sql);
        Assert.Contains("CREATE TRIGGER \"ORDERS_BI_ID\"", sql);
        Assert.Contains("NEXT VALUE FOR \"GEN_ORDERS_ID\"", sql);
        // Three top-level statements: CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER.
        var statements = FirebirdDdlExecutor.SplitStatements(sql);
        Assert.Equal(3, statements.Count);
    }

    [Fact]
    public void TableDescription_EmitsCommentOnTable()
    {
        var spec = MakeSpec();
        spec.Description = "Adresy klientów";
        var sql = DdlGenerator.BuildCreateTable("ADRES", spec);
        Assert.Contains("COMMENT ON TABLE \"ADRES\" IS 'Adresy klientów'", sql);
    }

    [Fact]
    public void FieldDescription_EmitsCommentOnColumn()
    {
        var spec = new TableSpec();
        spec.Fields.Add(new FieldDefinition
        {
            Name = "ID", BasicType = "INTEGER",
            Description = "Identifier",
        });
        var sql = DdlGenerator.BuildCreateTable("T", spec);
        Assert.Contains("COMMENT ON COLUMN \"T\".\"ID\" IS 'Identifier'", sql);
    }

    [Fact]
    public void CommentEscapesSingleQuotes()
    {
        var sql = DdlGenerator.BuildCommentTable("T", "Tom's notes");
        Assert.Contains("IS 'Tom''s notes'", sql);
    }
}

public class AlterFieldDdlTests
{
    [Fact]
    public void BuildRenameField_EmitsAlterTo()
    {
        var sql = DdlGenerator.BuildRenameField("T", "OLD", "NEW");
        Assert.Equal("ALTER TABLE \"T\" ALTER \"OLD\" TO \"NEW\"", sql);
    }

    [Fact]
    public void BuildSetNotNull_True_EmitsSet()
    {
        Assert.Equal(
            "ALTER TABLE \"T\" ALTER \"F\" SET NOT NULL",
            DdlGenerator.BuildSetNotNull("T", "F", true));
    }

    [Fact]
    public void BuildSetNotNull_False_EmitsDrop()
    {
        Assert.Equal(
            "ALTER TABLE \"T\" ALTER \"F\" DROP NOT NULL",
            DdlGenerator.BuildSetNotNull("T", "F", false));
    }

    [Fact]
    public void BuildSetDefault_WithValue_EmitsSetDefault()
    {
        Assert.Equal(
            "ALTER TABLE \"T\" ALTER \"F\" SET DEFAULT 0",
            DdlGenerator.BuildSetDefault("T", "F", "0"));
    }

    [Fact]
    public void BuildSetDefault_Null_EmitsDropDefault()
    {
        Assert.Equal(
            "ALTER TABLE \"T\" ALTER \"F\" DROP DEFAULT",
            DdlGenerator.BuildSetDefault("T", "F", null));
        Assert.Equal(
            "ALTER TABLE \"T\" ALTER \"F\" DROP DEFAULT",
            DdlGenerator.BuildSetDefault("T", "F", "  "));
    }

    [Fact]
    public void BuildAlterType_EmitsAlterType()
    {
        Assert.Equal(
            "ALTER TABLE \"T\" ALTER \"F\" TYPE VARCHAR(80)",
            DdlGenerator.BuildAlterType("T", "F", "VARCHAR(80)"));
    }

    [Fact]
    public void BuildCommentColumn_WithText_EmitsLiteral()
    {
        Assert.Equal(
            "COMMENT ON COLUMN \"T\".\"F\" IS 'hello'",
            DdlGenerator.BuildCommentColumn("T", "F", "hello"));
    }

    [Fact]
    public void BuildCommentColumn_NullOrEmpty_EmitsIsNull()
    {
        Assert.Equal(
            "COMMENT ON COLUMN \"T\".\"F\" IS NULL",
            DdlGenerator.BuildCommentColumn("T", "F", null));
        Assert.Equal(
            "COMMENT ON COLUMN \"T\".\"F\" IS NULL",
            DdlGenerator.BuildCommentColumn("T", "F", ""));
    }

    [Fact]
    public void Throws_OnEmptyArgs()
    {
        Assert.Throws<System.ArgumentException>(() => DdlGenerator.BuildRenameField("", "A", "B"));
        Assert.Throws<System.ArgumentException>(() => DdlGenerator.BuildSetNotNull("T", "", true));
        Assert.Throws<System.ArgumentException>(() => DdlGenerator.BuildAlterType("T", "F", "  "));
    }
}

public class FieldInfoAutoIncrementTests
{
    [Fact]
    public void IsAutoIncrement_DefaultsFalse()
    {
        var f = new FieldInfo { Name = "ID" };
        Assert.False(f.IsAutoIncrement);
    }

    [Fact]
    public void IsAutoIncrement_InitAssignment_RoundTrips()
    {
        var f = new FieldInfo { Name = "ID", IsAutoIncrement = true };
        Assert.True(f.IsAutoIncrement);
    }

    [Fact]
    public void FieldsSql_IncludesIsAiCase()
    {
        // Regression-pins the column shape: the reader expects column 17 to be IS_AI
        // (sourced from a CASE expression looking at RDB$IDENTITY_TYPE + trigger
        // existence). The CASE block names IDENTITY_TYPE explicitly.
        var sql = FirebirdTableDetailReader.FieldsSql;
        Assert.Contains("RDB$IDENTITY_TYPE", sql);
        Assert.Contains("RDB$TRIGGERS", sql);
        Assert.Contains("GEN_ID(", sql);
        Assert.Contains("AS IS_AI", sql);
    }
}
