/* ===================================================================
   EmberTern_Lab.fdb  —  laboratory schema (canonical recreate script)

   Target  : Firebird 5.0 (local DefaultInstance, localhost:3050)
   Charset : WIN1250 (set on the DB at CREATE DATABASE time)
   Scope   : a small, representative object zoo for hand-verifying
             EmberTern behaviour (metadata, DDL, dependencies, SQL).

   This script creates the SCHEMA OBJECTS ONLY. It assumes you are
   already CONNECTED to (or have just CREATEd) the target database.
   See Lab/README in CLAUDE.md for the exact recreate commands.

   Identifiers are intentionally ASCII so the script runs under any
   isql client charset. The database default charset is WIN1250.
   =================================================================== */

/* ---------- Domains -------------------------------------------------
   Cover: VARCHAR, CHAR, INTEGER, NUMERIC, DATE, TIMESTAMP, BLOB,
          DEFAULT, CHECK, NOT NULL.                                   */

CREATE DOMAIN D_NAME      AS VARCHAR(60) NOT NULL;
CREATE DOMAIN D_CODE      AS CHAR(8);
CREATE DOMAIN D_AMOUNT    AS NUMERIC(15,2) DEFAULT 0 NOT NULL CHECK (VALUE >= 0);
CREATE DOMAIN D_QTY       AS INTEGER DEFAULT 1 CHECK (VALUE > 0);
CREATE DOMAIN D_CREATED   AS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
CREATE DOMAIN D_BIRTHDATE AS DATE;
CREATE DOMAIN D_FLAG      AS CHAR(1) DEFAULT 'N' CHECK (VALUE IN ('Y','N'));
CREATE DOMAIN D_NOTES     AS BLOB SUB_TYPE TEXT;

/* ---------- Generators / sequences ---------------------------------
   Cover: standard, START WITH, START WITH + INCREMENT BY.            */

CREATE SEQUENCE GEN_CUSTOMER_ID;
CREATE SEQUENCE GEN_ORDER_ID   START WITH 1000;
CREATE SEQUENCE GEN_INVOICE_NO START WITH 5000 INCREMENT BY 10;

/* ---------- Exceptions --------------------------------------------- */

CREATE EXCEPTION E_CUSTOMER_NOT_FOUND 'Customer not found.';
CREATE EXCEPTION E_NEGATIVE_AMOUNT    'Amount must not be negative.';
CREATE EXCEPTION E_ORDER_LOCKED       'Order is locked and cannot be modified.';

/* ---------- Roles -------------------------------------------------- */

CREATE ROLE LAB_READER;
CREATE ROLE LAB_EDITOR;
CREATE ROLE LAB_ADMIN;

/* ---------- Tables --------------------------------------------------
   Cover: PK, FK, composite PK, unique, computed fields, identity
          (BY DEFAULT and ALWAYS), fields using domains.              */

CREATE TABLE CUSTOMERS (
  CUSTOMER_ID INTEGER GENERATED BY DEFAULT AS IDENTITY,
  CODE        D_CODE,
  NAME        D_NAME,
  EMAIL       VARCHAR(120),
  BIRTH_DATE  D_BIRTHDATE,
  IS_ACTIVE   D_FLAG,
  CREATED_AT  D_CREATED,
  CONSTRAINT PK_CUSTOMERS      PRIMARY KEY (CUSTOMER_ID),
  CONSTRAINT UQ_CUSTOMERS_CODE UNIQUE (CODE),
  CONSTRAINT UQ_CUSTOMERS_MAIL UNIQUE (EMAIL)
);

CREATE TABLE PRODUCTS (
  PRODUCT_ID     INTEGER GENERATED ALWAYS AS IDENTITY,
  SKU            D_CODE NOT NULL,
  NAME           D_NAME,
  UNIT_PRICE     D_AMOUNT,
  TAX_RATE       NUMERIC(5,2) DEFAULT 23 NOT NULL,
  PRICE_WITH_TAX COMPUTED BY (UNIT_PRICE * (1 + TAX_RATE / 100)),
  CONSTRAINT PK_PRODUCTS     PRIMARY KEY (PRODUCT_ID),
  CONSTRAINT UQ_PRODUCTS_SKU UNIQUE (SKU)
);

CREATE TABLE ORDERS (
  ORDER_ID     INTEGER NOT NULL,
  CUSTOMER_ID  INTEGER NOT NULL,
  ORDER_DATE   D_CREATED,
  STATUS       D_CODE DEFAULT 'NEW',
  TOTAL_AMOUNT D_AMOUNT,
  CONSTRAINT PK_ORDERS       PRIMARY KEY (ORDER_ID),
  CONSTRAINT FK_ORDERS_CUST  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID)
);

CREATE TABLE ORDER_ITEMS (
  ORDER_ID   INTEGER NOT NULL,
  LINE_NO    INTEGER NOT NULL,
  PRODUCT_ID INTEGER NOT NULL,
  QTY        D_QTY,
  UNIT_PRICE D_AMOUNT,
  LINE_TOTAL COMPUTED BY (QTY * UNIT_PRICE),
  CONSTRAINT PK_ORDER_ITEMS  PRIMARY KEY (ORDER_ID, LINE_NO),
  CONSTRAINT FK_ITEMS_ORDER  FOREIGN KEY (ORDER_ID)   REFERENCES ORDERS (ORDER_ID),
  CONSTRAINT FK_ITEMS_PROD   FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID)
);

CREATE TABLE AUDIT_LOG (
  LOG_ID    INTEGER GENERATED BY DEFAULT AS IDENTITY,
  ENTITY    VARCHAR(30) NOT NULL,
  ENTITY_ID INTEGER,
  ACTION    VARCHAR(20),
  DETAILS   D_NOTES,
  LOGGED_AT D_CREATED,
  CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (LOG_ID)
);

/* ---------- Standalone indexes --------------------------------------
   Exercise the Index Detail surface: a plain index, a DESCENDING index,
   a composite index, a standalone UNIQUE index, an expression index, and
   one INACTIVE index. (PK / FK / UNIQUE *constraint* backing indexes are
   created implicitly by the table constraints above.)                */

CREATE INDEX IDX_ORDERS_DATE          ON ORDERS (ORDER_DATE);
CREATE DESCENDING INDEX IDX_ORDERS_AMT ON ORDERS (TOTAL_AMOUNT);
CREATE INDEX IDX_ITEMS_PROD_QTY       ON ORDER_ITEMS (PRODUCT_ID, QTY);
CREATE UNIQUE INDEX IDX_CUST_EMAIL_U  ON CUSTOMERS (EMAIL);
CREATE INDEX IDX_CUST_NAME_UPPER      ON CUSTOMERS COMPUTED BY (UPPER(NAME));
CREATE INDEX IDX_ORDERS_STATUS        ON ORDERS (STATUS);
ALTER INDEX IDX_ORDERS_STATUS INACTIVE;
COMMENT ON INDEX IDX_ORDERS_DATE IS 'Lookup orders by date (lab).';

/* ---------- Views ---------------------------------------------------
   Cover: simple, join, aggregate.                                    */

CREATE VIEW V_ACTIVE_CUSTOMERS AS
  SELECT CUSTOMER_ID, CODE, NAME, EMAIL
  FROM CUSTOMERS
  WHERE IS_ACTIVE = 'Y';

CREATE VIEW V_ORDER_DETAILS AS
  SELECT o.ORDER_ID,
         c.NAME       AS CUSTOMER_NAME,
         oi.LINE_NO,
         p.NAME       AS PRODUCT_NAME,
         oi.QTY,
         oi.UNIT_PRICE,
         oi.LINE_TOTAL
  FROM ORDERS o
  JOIN CUSTOMERS   c  ON c.CUSTOMER_ID = o.CUSTOMER_ID
  JOIN ORDER_ITEMS oi ON oi.ORDER_ID   = o.ORDER_ID
  JOIN PRODUCTS    p  ON p.PRODUCT_ID  = oi.PRODUCT_ID;

CREATE VIEW V_CUSTOMER_TOTALS AS
  SELECT c.CUSTOMER_ID,
         c.NAME,
         COUNT(o.ORDER_ID)              AS ORDER_COUNT,
         COALESCE(SUM(o.TOTAL_AMOUNT),0) AS TOTAL_SPENT
  FROM CUSTOMERS c
  LEFT JOIN ORDERS o ON o.CUSTOMER_ID = c.CUSTOMER_ID
  GROUP BY c.CUSTOMER_ID, c.NAME;

/* ---------- Functions (PSQL) ---------------------------------------
   Cover: scalar functions with params, DECLARE, IF/ELSE, RETURN.    */

SET TERM ^ ;

CREATE FUNCTION FN_ADD_TAX(AMOUNT NUMERIC(15,2), RATE NUMERIC(5,2))
RETURNS NUMERIC(15,2)
AS
BEGIN
  RETURN AMOUNT * (1 + RATE / 100);
END^

CREATE FUNCTION FN_FULL_LABEL(CODE VARCHAR(8), NAME VARCHAR(60))
RETURNS VARCHAR(80)
AS
  DECLARE VARIABLE RESULT VARCHAR(80);
BEGIN
  IF (CODE IS NULL) THEN
    RESULT = NAME;
  ELSE
    RESULT = TRIM(CODE) || ' - ' || NAME;
  RETURN RESULT;
END^

SET TERM ; ^

/* ---------- Procedures (PSQL) --------------------------------------
   Cover: input/output params, SUSPEND, CASE, nested BEGIN/END,
          FOR SELECT, exceptions.                                    */

SET TERM ^ ;

CREATE PROCEDURE SP_CUSTOMER_ORDERS(P_CUSTOMER_ID INTEGER)
RETURNS (ORDER_ID INTEGER,
         ORDER_DATE TIMESTAMP,
         STATUS_LABEL VARCHAR(20),
         TOTAL_AMOUNT NUMERIC(15,2))
AS
  DECLARE VARIABLE V_STATUS CHAR(8);
BEGIN
  FOR SELECT o.ORDER_ID, o.ORDER_DATE, o.STATUS, o.TOTAL_AMOUNT
      FROM ORDERS o
      WHERE o.CUSTOMER_ID = :P_CUSTOMER_ID
      INTO :ORDER_ID, :ORDER_DATE, :V_STATUS, :TOTAL_AMOUNT
  DO
  BEGIN
    STATUS_LABEL = CASE TRIM(V_STATUS)
                     WHEN 'NEW'  THEN 'New'
                     WHEN 'PAID' THEN 'Paid'
                     WHEN 'SHIP' THEN 'Shipped'
                     ELSE 'Unknown'
                   END;
    SUSPEND;
  END
END^

CREATE PROCEDURE SP_ADD_ORDER(P_CUSTOMER_ID INTEGER,
                              P_AMOUNT      NUMERIC(15,2))
RETURNS (NEW_ORDER_ID INTEGER)
AS
  DECLARE VARIABLE V_EXISTS INTEGER;
BEGIN
  SELECT COUNT(*) FROM CUSTOMERS
    WHERE CUSTOMER_ID = :P_CUSTOMER_ID
    INTO :V_EXISTS;

  IF (V_EXISTS = 0) THEN
    EXCEPTION E_CUSTOMER_NOT_FOUND;

  IF (P_AMOUNT < 0) THEN
    EXCEPTION E_NEGATIVE_AMOUNT;

  NEW_ORDER_ID = NEXT VALUE FOR GEN_ORDER_ID;
  INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, TOTAL_AMOUNT, STATUS)
    VALUES (:NEW_ORDER_ID, :P_CUSTOMER_ID, :P_AMOUNT, 'NEW');
  SUSPEND;
END^

/* ---------- Debugger zoo (Stage X / D2) ----------------------------
   D2 step units: assignment, IF/ELSE, a domain NOT NULL local (declared
   but not assigned at entry — must not crash under the harness, §3.4 R1),
   SUSPEND, and a WHEN … DO exception handler caught through the real
   FbException → DebugError mapping. Nested calls / cursors / local
   routines / autonomous tx grow this zoo per their own milestones
   (D6/D8/D9), which is where the debugger can step them.               */

CREATE PROCEDURE SP_DBG_SUMMARY(P_QTY INTEGER, P_PRICE NUMERIC(15,2))
RETURNS (LINE_TOTAL NUMERIC(15,2), LABEL VARCHAR(20))
AS
  DECLARE VARIABLE V_TOTAL D_AMOUNT NOT NULL;   /* domain NOT NULL local */
BEGIN
  V_TOTAL = P_QTY * P_PRICE;
  IF (V_TOTAL > 100) THEN
    LABEL = 'BIG';
  ELSE
    LABEL = 'SMALL';
  LINE_TOTAL = V_TOTAL;
  SUSPEND;
END^

CREATE PROCEDURE SP_DBG_GUARD(P_AMOUNT NUMERIC(15,2))
RETURNS (RESULT VARCHAR(20))
AS
BEGIN
  BEGIN
    IF (P_AMOUNT < 0) THEN
      EXCEPTION E_NEGATIVE_AMOUNT;
    RESULT = 'OK';
  WHEN EXCEPTION E_NEGATIVE_AMOUNT DO
    RESULT = 'CAUGHT';
  END
  SUSPEND;
END^

/* D6 (Cursor Bridge): a single FOR SELECT over ORDER_ITEMS. Exercises a colon-param WHERE
   (:P_ORDER, a native DSQL bind), INTO colon targets mapped positionally, a body that reads
   /writes a running-sum local, and SUSPEND emitting one row per iteration.
   SP_DBG_CURSOR(1000) => (1, 20.00, 20.00), (2, 25.50, 45.50); (1001) => (1, 20.00, 20.00). */
CREATE PROCEDURE SP_DBG_CURSOR(P_ORDER INTEGER)
RETURNS (LINE_NO INTEGER, AMOUNT NUMERIC(15,2), RUNNING NUMERIC(15,2))
AS
  DECLARE VARIABLE V_SUM NUMERIC(15,2);
BEGIN
  V_SUM = 0;
  FOR SELECT LINE_NO, QTY * UNIT_PRICE
      FROM ORDER_ITEMS
      WHERE ORDER_ID = :P_ORDER
      ORDER BY LINE_NO
      INTO :LINE_NO, :AMOUNT DO
  BEGIN
    V_SUM = V_SUM + AMOUNT;
    RUNNING = V_SUM;
    SUSPEND;
  END
END^

/* D6 (Cursor Bridge): NESTED FOR SELECT — two cursors open simultaneously (outer ORDERS, inner
   ORDER_ITEMS per order). The inner cursor's WHERE references the outer frame's local (:V_OID),
   proving frame injection + concurrent cursors (probe [4]).
   SP_DBG_NESTED => (1000, 2), (1001, 1). */
CREATE PROCEDURE SP_DBG_NESTED
RETURNS (ORDER_ID INTEGER, ITEM_COUNT INTEGER)
AS
  DECLARE VARIABLE V_OID INTEGER;
  DECLARE VARIABLE V_LINE INTEGER;
  DECLARE VARIABLE V_CNT INTEGER;
BEGIN
  FOR SELECT ORDER_ID FROM ORDERS ORDER BY ORDER_ID INTO :V_OID DO
  BEGIN
    V_CNT = 0;
    FOR SELECT LINE_NO FROM ORDER_ITEMS WHERE ORDER_ID = :V_OID INTO :V_LINE DO
      V_CNT = V_CNT + 1;
    ORDER_ID = V_OID;
    ITEM_COUNT = V_CNT;
    SUSPEND;
  END
END^

/* D8 (Call stack + nested stored routines): a THREE-level call chain proving step-into a stored
   procedure — argument seeding (each level passes its param down) and RETURNING_VALUES write-back
   (each callee's output binds into the caller's local). SP_DBG_LEAF and SP_DBG_MID are EXECUTABLE
   (no SUSPEND → called via EXECUTE PROCEDURE); SP_DBG_ROOT is selectable.
   SP_DBG_ROOT(5): LEAF(5)=6, MID=6*2=12, ROOT=12+100=112 => RESULT = 112. */
CREATE PROCEDURE SP_DBG_LEAF(P INTEGER)
RETURNS (Q INTEGER)
AS
BEGIN
  Q = P + 1;
END^

CREATE PROCEDURE SP_DBG_MID(P INTEGER)
RETURNS (Q INTEGER)
AS
  DECLARE VARIABLE T INTEGER;
BEGIN
  EXECUTE PROCEDURE SP_DBG_LEAF(:P) RETURNING_VALUES :T;
  Q = T * 2;
END^

CREATE PROCEDURE SP_DBG_ROOT(P INTEGER)
RETURNS (RESULT INTEGER)
AS
  DECLARE VARIABLE T INTEGER;
BEGIN
  EXECUTE PROCEDURE SP_DBG_MID(:P) RETURNING_VALUES :T;
  RESULT = T + 100;
  SUSPEND;
END^

/* D9 (Local procedures & functions — the flagship): a routine with a local FUNCTION (TRIPLE) and a
   local PROCEDURE (ADD_TAX), proving STEP INTO a local sub-procedure as a real debugger frame — argument
   seeding (ACC → AMOUNT) + RETURNING_VALUES write-back (WITH_TAX → TOTAL), a local variable inside the
   sub-procedure (BONUS), and a local function exercised server-side (a faithful step-over, carried into the
   harness verbatim as R5). Each sub-routine is SELF-CONTAINED (no outer-variable closure — that is D9
   seam b); the local procedure's parameters have no RDB$PROCEDURE_PARAMETERS row, so the debugger derives
   their types from the AST header. SP_DBG_LOCAL(5): TRIPLE(5)=15, ADD_TAX(15): BONUS=100, WITH_TAX=115
   => TOTAL = 115. */
CREATE PROCEDURE SP_DBG_LOCAL(BASE INTEGER)
RETURNS (TOTAL INTEGER)
AS
  DECLARE FUNCTION TRIPLE(N INTEGER) RETURNS INTEGER
  AS
  BEGIN
    RETURN N * 3;
  END
  DECLARE PROCEDURE ADD_TAX(AMOUNT INTEGER) RETURNS (WITH_TAX INTEGER)
  AS
    DECLARE VARIABLE BONUS INTEGER;
  BEGIN
    BONUS = 100;
    WITH_TAX = AMOUNT + BONUS;
  END
  DECLARE VARIABLE ACC INTEGER;
BEGIN
  ACC = TRIPLE(BASE);
  EXECUTE PROCEDURE ADD_TAX(:ACC) RETURNING_VALUES :TOTAL;
  SUSPEND;
END^

/* D9 seam (b) — closure capture: a local PROCEDURE BUMP that READS and WRITES an OUTER variable (ACC),
   proving Step Into a local routine whose body captures the declaring frame's variable (an FB5 closure,
   §6.1/§6.2b). The debugger declares + injects + writes back the captured outer variable in BUMP's harness,
   and the closure write reaches the parent frame. FB3 could not compile this (closed scopes, §6.3) — the lab
   is FB5, so this is a legitimate zoo member. SP_DBG_CLOSURE(5): ACC=5, BUMP→15, BUMP→25 => TOTAL = 25. */
CREATE PROCEDURE SP_DBG_CLOSURE(SEED INTEGER)
RETURNS (TOTAL INTEGER)
AS
  DECLARE VARIABLE ACC INTEGER;
  DECLARE PROCEDURE BUMP
  AS
  BEGIN
    ACC = ACC + 10;
  END
BEGIN
  ACC = SEED;
  EXECUTE PROCEDURE BUMP;
  EXECUTE PROCEDURE BUMP;
  TOTAL = ACC;
  SUSPEND;
END^

/* D9 seam (b) Part 2 — transitive read/write-set fixpoint (Step OVER a local call with a HIDDEN capture).
   A local FUNCTION BUMP_HIDDEN reads+writes the outer variable HIDDEN, which is NOT mentioned at the call
   site (the call passes only the literal 10). Without the call-graph fixpoint the debugger would inject
   HIDDEN as NULL and drop its mutation; with it, HIDDEN is injected + written back. Exercised as a natural
   step-over (a function call inside a leaf runs server-side). SP_DBG_CLOSURE_FN(5): HIDDEN=5, BUMP_HIDDEN(10)
   => HIDDEN=15, returns 15 => TOTAL = 15. */
CREATE PROCEDURE SP_DBG_CLOSURE_FN(SEED INTEGER)
RETURNS (TOTAL INTEGER)
AS
  DECLARE VARIABLE HIDDEN INTEGER;
  DECLARE FUNCTION BUMP_HIDDEN(DELTA INTEGER) RETURNS INTEGER
  AS
  BEGIN
    HIDDEN = HIDDEN + DELTA;
    RETURN HIDDEN;
  END
BEGIN
  HIDDEN = SEED;
  TOTAL = BUMP_HIDDEN(10);
  SUSPEND;
END^

/* D9 seam (b) Part 2 — the same fixpoint for a local PROCEDURE stepped OVER. ACCUMULATE reads+writes the
   outer HIDDEN (a hidden capture — the call passes only the literal 10 and returns into TOTAL). Proven with
   Step Over on the call. SP_DBG_CLOSURE_OVER(5): HIDDEN=5, ACCUMULATE(10) => HIDDEN=15, RESULT=15
   => TOTAL = 15. */
CREATE PROCEDURE SP_DBG_CLOSURE_OVER(SEED INTEGER)
RETURNS (TOTAL INTEGER)
AS
  DECLARE VARIABLE HIDDEN INTEGER;
  DECLARE PROCEDURE ACCUMULATE(DELTA INTEGER) RETURNS (RESULT INTEGER)
  AS
  BEGIN
    HIDDEN = HIDDEN + DELTA;
    RESULT = HIDDEN;
  END
BEGIN
  HIDDEN = SEED;
  EXECUTE PROCEDURE ACCUMULATE(10) RETURNING_VALUES :TOTAL;
  SUSPEND;
END^

/* D9 seam (c) — step INTO a local FUNCTION in each of the four value-consuming positions (§6.4): an
   assignment RHS (V = INC(P)), a RETURN operand (inside WRAP: RETURN INC(N)), an IF condition
   (IF (POSITIVE(V))), and a WHILE condition (WHILE (POSITIVE(3 - I))). Each call is the ENTIRE operand, so
   the debugger descends without evaluating a surrounding expression; the return value is delivered to the
   caller position client-side. Depth reaches 3 (SP_DBG_FN_POS → WRAP → INC via the RETURN operand).
   SP_DBG_FN_POS(5): V=INC(5)=6; POSITIVE(6) → V=WRAP(6)=INC(6)=7; loop POSITIVE(3),(2),(1) true, (0) false
   → I=3; RESULT = 7 + 3 = 10. */
CREATE PROCEDURE SP_DBG_FN_POS(P INTEGER)
RETURNS (RESULT INTEGER)
AS
  DECLARE FUNCTION INC(N INTEGER) RETURNS INTEGER AS BEGIN RETURN N + 1; END
  DECLARE FUNCTION POSITIVE(N INTEGER) RETURNS BOOLEAN AS BEGIN RETURN N > 0; END
  DECLARE FUNCTION WRAP(N INTEGER) RETURNS INTEGER AS BEGIN RETURN INC(N); END
  DECLARE VARIABLE V INTEGER;
  DECLARE VARIABLE I INTEGER;
BEGIN
  V = INC(P);
  IF (POSITIVE(V)) THEN
    V = WRAP(V);
  I = 0;
  WHILE (POSITIVE(3 - I)) DO
    I = I + 1;
  RESULT = V + I;
  SUSPEND;
END^

/* D9 seam (c) — the Expression Harness must reproduce the server's RETURN value across diverse types. Each
   local function returns a different type; each is stepped INTO (an assignment RHS) and its RETURN operand is
   computed by the Expression Harness typed as the function's RETURNS base type (R2). Covers INTEGER, BIGINT
   (a value beyond INT32), NUMERIC, VARCHAR, BOOLEAN, and NULL. Every output column is compared simulated vs
   real. */
CREATE PROCEDURE SP_DBG_FN_TYPES
RETURNS (R_INT INTEGER, R_BIG BIGINT, R_NUM NUMERIC(15,2), R_TXT VARCHAR(20), R_BOOL BOOLEAN, R_NUL INTEGER)
AS
  DECLARE FUNCTION F_INT RETURNS INTEGER AS BEGIN RETURN 42; END
  DECLARE FUNCTION F_BIG RETURNS BIGINT AS BEGIN RETURN 9000000000; END
  DECLARE FUNCTION F_NUM RETURNS NUMERIC(15,2) AS BEGIN RETURN 3.14; END
  DECLARE FUNCTION F_TXT RETURNS VARCHAR(20) AS BEGIN RETURN 'hello'; END
  DECLARE FUNCTION F_BOOL RETURNS BOOLEAN AS BEGIN RETURN TRUE; END
  DECLARE FUNCTION F_NUL RETURNS INTEGER AS BEGIN RETURN NULL; END
BEGIN
  R_INT = F_INT();
  R_BIG = F_BIG();
  R_NUM = F_NUM();
  R_TXT = F_TXT();
  R_BOOL = F_BOOL();
  R_NUL = F_NUL();
  SUSPEND;
END^

/* D9 seam (c) — ResolveFunction lexical SHADOWING + choosing the correct definition. FN_ADD_TAX exists as a
   standalone stored FUNCTION (defined above); here a LOCAL function of the same name shadows it. Firebird
   resolves the call to the LOCAL sub-routine (a local declaration shadows a global one), so the debugger must
   ALSO pick the local — step INTO it (depth 2) — rather than treating the name as the global stored function
   (which would step over, depth 1). depth == 2 proves the local definition was chosen; simulated == real ==
   P + 5000 proves fidelity. (Firebird does not permit sub-routines nested inside sub-routines, so lexical
   shadowing across sub-routine levels is not expressible — local-vs-global is the realistic case.)
   SP_DBG_FN_SHADOW(5) → 5005. */
CREATE PROCEDURE SP_DBG_FN_SHADOW(P INTEGER)
RETURNS (RESULT INTEGER)
AS
  DECLARE FUNCTION FN_ADD_TAX(N INTEGER) RETURNS INTEGER AS BEGIN RETURN N + 5000; END
BEGIN
  RESULT = FN_ADD_TAX(P);
  SUSPEND;
END^

/* D9 seam (c) — step INTO a local FUNCTION that CLOSES OVER an outer variable (an FB5 closure, §6.2b): the
   function reads BASE, which is not one of its parameters. Stepping into RESULT = ADD_BASE(P) descends into
   ADD_BASE, whose harness declares + injects the captured outer BASE, so RETURN N + BASE computes correctly.
   SP_DBG_FN_CLOSURE(5): BASE=100, ADD_BASE(5) = 5 + 100 = 105 → RESULT = 105. */
CREATE PROCEDURE SP_DBG_FN_CLOSURE(P INTEGER)
RETURNS (RESULT INTEGER)
AS
  DECLARE VARIABLE BASE INTEGER;
  DECLARE FUNCTION ADD_BASE(N INTEGER) RETURNS INTEGER AS BEGIN RETURN N + BASE; END
BEGIN
  BASE = 100;
  RESULT = ADD_BASE(P);
  SUSPEND;
END^

SET TERM ; ^

/* ---------- Triggers (PSQL) ----------------------------------------
   Cover: before insert, before update, after update.                */

SET TERM ^ ;

CREATE TRIGGER TR_ORDERS_BI FOR ORDERS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ORDER_ID IS NULL) THEN
    NEW.ORDER_ID = NEXT VALUE FOR GEN_ORDER_ID;
  IF (NEW.ORDER_DATE IS NULL) THEN
    NEW.ORDER_DATE = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TR_ORDERS_BU FOR ORDERS
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
  IF (NEW.TOTAL_AMOUNT < 0) THEN
    EXCEPTION E_NEGATIVE_AMOUNT;
END^

CREATE TRIGGER TR_ORDERS_AU FOR ORDERS
ACTIVE AFTER UPDATE POSITION 0
AS
BEGIN
  IF (OLD.STATUS IS DISTINCT FROM NEW.STATUS) THEN
    INSERT INTO AUDIT_LOG (ENTITY, ENTITY_ID, ACTION, DETAILS)
      VALUES ('ORDERS', NEW.ORDER_ID, 'STATUS_CHANGE',
              'Status changed from ' || TRIM(OLD.STATUS) || ' to ' || TRIM(NEW.STATUS));
END^

SET TERM ; ^

/* ---------- Package + body (PSQL) ----------------------------------
   Cover: package header + body, with a function and a procedure.     */

SET TERM ^ ;

CREATE PACKAGE PKG_ORDERS
AS
BEGIN
  FUNCTION  ORDER_TOTAL(P_ORDER_ID INTEGER) RETURNS NUMERIC(15,2);
  PROCEDURE RECALC_ORDER(P_ORDER_ID INTEGER);
END^

CREATE PACKAGE BODY PKG_ORDERS
AS
BEGIN
  FUNCTION ORDER_TOTAL(P_ORDER_ID INTEGER) RETURNS NUMERIC(15,2)
  AS
    DECLARE VARIABLE V_TOTAL NUMERIC(15,2);
  BEGIN
    SELECT COALESCE(SUM(LINE_TOTAL), 0) FROM ORDER_ITEMS
      WHERE ORDER_ID = :P_ORDER_ID
      INTO :V_TOTAL;
    RETURN V_TOTAL;
  END

  PROCEDURE RECALC_ORDER(P_ORDER_ID INTEGER)
  AS
  BEGIN
    UPDATE ORDERS SET TOTAL_AMOUNT = PKG_ORDERS.ORDER_TOTAL(:P_ORDER_ID)
      WHERE ORDER_ID = :P_ORDER_ID;
  END
END^

SET TERM ; ^

/* ---------- Descriptions (exercise COMMENT ON metadata) ------------ */

COMMENT ON TABLE  CUSTOMERS              IS 'Customers master table (lab).';
COMMENT ON TABLE  ORDERS                 IS 'Sales orders (lab).';
COMMENT ON DOMAIN D_AMOUNT               IS 'Non-negative monetary amount, 2 decimals.';
COMMENT ON PROCEDURE SP_CUSTOMER_ORDERS  IS 'Selectable: orders for a given customer with a friendly status label.';
COMMENT ON ROLE   LAB_READER             IS 'Read-only access to the lab schema.';
COMMENT ON ROLE   LAB_EDITOR             IS 'Read/write access to orders.';

/* ---------- Privileges + role membership (Security Manager lab data) -------
   Object, column, EXECUTE and USAGE grants to the lab roles, plus role-to-role
   membership — gives the Security Manager's Privileges / Membership panes real
   rows to display. All per-database (safe to seed; users are server-global and
   cannot be created here).                                                    */

GRANT SELECT ON CUSTOMERS TO LAB_READER;
GRANT SELECT ON ORDERS    TO LAB_READER;
GRANT SELECT ON PRODUCTS  TO LAB_READER;

GRANT SELECT, INSERT, UPDATE, DELETE ON ORDERS TO LAB_EDITOR;
GRANT UPDATE (EMAIL) ON CUSTOMERS TO LAB_EDITOR;
GRANT REFERENCES (CUSTOMER_ID) ON CUSTOMERS TO LAB_EDITOR;
GRANT SELECT ON V_ORDER_DETAILS TO LAB_READER WITH GRANT OPTION;

GRANT EXECUTE ON PROCEDURE SP_CUSTOMER_ORDERS TO LAB_READER;
GRANT USAGE ON SEQUENCE GEN_ORDER_ID TO LAB_EDITOR;
GRANT USAGE ON EXCEPTION E_ORDER_LOCKED TO LAB_READER;

GRANT LAB_READER TO LAB_EDITOR;
GRANT LAB_EDITOR TO LAB_ADMIN WITH ADMIN OPTION;

/* ---------- Sample data --------------------------------------------
   Deterministic explicit ids so FKs and views show real rows.
   ASCII only (DB charset is WIN1250; ASCII is a valid subset).       */

INSERT INTO CUSTOMERS (CUSTOMER_ID, CODE, NAME, EMAIL, BIRTH_DATE, IS_ACTIVE)
  VALUES (1, 'CUST0001', 'Acme Corporation', 'contact@acme.example', DATE '1990-04-12', 'Y');
INSERT INTO CUSTOMERS (CUSTOMER_ID, CODE, NAME, EMAIL, BIRTH_DATE, IS_ACTIVE)
  VALUES (2, 'CUST0002', 'Globex LLC', 'sales@globex.example', DATE '1985-11-30', 'Y');
INSERT INTO CUSTOMERS (CUSTOMER_ID, CODE, NAME, EMAIL, BIRTH_DATE, IS_ACTIVE)
  VALUES (3, 'CUST0003', 'Initech', 'info@initech.example', NULL, 'N');

INSERT INTO PRODUCTS (PRODUCT_ID, SKU, NAME, UNIT_PRICE, TAX_RATE)
  OVERRIDING SYSTEM VALUE VALUES (1, 'PRD-0001', 'Widget',  10.00, 23);
INSERT INTO PRODUCTS (PRODUCT_ID, SKU, NAME, UNIT_PRICE, TAX_RATE)
  OVERRIDING SYSTEM VALUE VALUES (2, 'PRD-0002', 'Gadget',  25.50, 23);
INSERT INTO PRODUCTS (PRODUCT_ID, SKU, NAME, UNIT_PRICE, TAX_RATE)
  OVERRIDING SYSTEM VALUE VALUES (3, 'PRD-0003', 'Gizmo',    5.00,  8);

INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, STATUS, TOTAL_AMOUNT)
  VALUES (1000, 1, 'PAID', 45.50);
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, STATUS, TOTAL_AMOUNT)
  VALUES (1001, 2, 'NEW', 20.00);

INSERT INTO ORDER_ITEMS (ORDER_ID, LINE_NO, PRODUCT_ID, QTY, UNIT_PRICE)
  VALUES (1000, 1, 1, 2, 10.00);
INSERT INTO ORDER_ITEMS (ORDER_ID, LINE_NO, PRODUCT_ID, QTY, UNIT_PRICE)
  VALUES (1000, 2, 2, 1, 25.50);
INSERT INTO ORDER_ITEMS (ORDER_ID, LINE_NO, PRODUCT_ID, QTY, UNIT_PRICE)
  VALUES (1001, 1, 3, 4, 5.00);

COMMIT;
