namespace EmberTern.Core.Metadata;

/// <summary>
/// How an identity column's value is generated (FB3+ <c>GENERATED … AS IDENTITY</c>) — decoded from
/// <c>RDB$RELATION_FIELDS.RDB$IDENTITY_TYPE</c>, whose encoding is <b>measured, not assumed</b>:
/// <c>0</c> = ALWAYS, <c>1</c> = BY DEFAULT (verified against a live FB5 engine by creating one of each
/// and reading the catalog back).
/// <para>
/// <b>Why the distinction has to exist</b> — it is not cosmetic. Firebird <em>rejects</em> an INSERT
/// that names a <c>GENERATED ALWAYS</c> column: <em>"OVERRIDING clause should be used when an identity
/// column defined as 'GENERATED ALWAYS' is present in the INSERT's field list"</em>. Generated DML must
/// therefore emit <c>OVERRIDING SYSTEM VALUE</c> for ALWAYS and must not for BY DEFAULT — and until this
/// enum existed the codebase collapsed both into a single bool, so the fact was simply unavailable.
/// (The lab's own <c>PRODUCTS.PRODUCT_ID</c> is <c>GENERATED ALWAYS</c>, so the naive INSERT fails on the
/// user's own database.)
/// </para>
/// </summary>
public enum IdentityKind
{
    /// <summary>Not an identity column.</summary>
    None = 0,

    /// <summary><c>GENERATED ALWAYS AS IDENTITY</c> — an INSERT naming it needs
    /// <c>OVERRIDING SYSTEM VALUE</c>.</summary>
    Always,

    /// <summary><c>GENERATED BY DEFAULT AS IDENTITY</c> — an INSERT may name it freely.</summary>
    ByDefault,
}

/// <summary>
/// Column name + formatted SQL type (e.g. "INTEGER", "VARCHAR(50)",
/// "NUMERIC(15,2)"), plus the user-defined domain (when the column is domain-typed)
/// and its nullability. Used by the SQL editor autocomplete to render
/// "COLUMN_NAME : TYPE : DOMAIN" entries after <c>ALIAS.</c> / <c>TABLE.</c> and to
/// feed the completion detail pane and Quick Info (Etap 6 P2 / Package 5).
/// <para>
/// The positional fields (<see cref="Name"/>/<see cref="Type"/>/<see cref="Domain"/>/
/// <see cref="NotNull"/>) are the light, hot-path essentials; the init-only properties
/// below are the <b>rich-but-optional</b> Quick Info facts (Package 5, Stage A) — a key
/// classification, a default/computed expression, a description — filled by
/// <see cref="EmberTern.Firebird"/>'s enriched columns query. They default to empty/false
/// so every existing positional call site (<c>new ColumnSpec(name, type)</c>) is
/// unaffected, and a provider that only knows name+type still produces a valid spec.
/// </para>
/// </summary>
/// <param name="Name">Column name (catalog-cased).</param>
/// <param name="Type">Formatted SQL type.</param>
/// <param name="Domain">User-defined domain name when the column is domain-typed,
/// else <c>null</c> (anonymous <c>RDB$…</c> backing domains are normalized away).</param>
/// <param name="NotNull"><c>true</c> when the column is declared NOT NULL.</param>
public sealed record ColumnSpec(string Name, string Type, string? Domain = null, bool NotNull = false)
{
    /// <summary>The column's default-value expression (the <c>DEFAULT</c>/<c>=</c> prefix
    /// stripped), else <c>null</c>.</summary>
    public string? DefaultValue { get; init; }

    /// <summary>The column's comment/description (<c>COMMENT ON COLUMN</c>), else <c>null</c>.</summary>
    public string? Description { get; init; }

    /// <summary><c>true</c> when the column participates in the table's PRIMARY KEY.</summary>
    public bool IsPrimaryKey { get; init; }

    /// <summary><c>true</c> when the column participates in a FOREIGN KEY.</summary>
    public bool IsForeignKey { get; init; }

    /// <summary>The referenced table for a foreign-key column, else <c>null</c>.</summary>
    public string? ForeignKeyTable { get; init; }

    /// <summary><c>true</c> when the column is <c>COMPUTED BY</c>.</summary>
    public bool IsComputed { get; init; }

    /// <summary>How the column's identity value is generated, or <see cref="IdentityKind.None"/> when it
    /// is not an identity column. ALWAYS vs BY DEFAULT changes what a valid INSERT looks like — see
    /// <see cref="IdentityKind"/>.</summary>
    public IdentityKind Identity { get; init; }

    /// <summary><c>true</c> when the column is an identity column (FB3+ <c>GENERATED … AS IDENTITY</c>).
    /// <b>Derived</b> from <see cref="Identity"/> rather than stored beside it: two fields that can
    /// disagree is how the ALWAYS/BY DEFAULT fact would rot back out of the model.</summary>
    public bool IsIdentity => Identity != IdentityKind.None;
}
