using System;
using System.Globalization;
using System.Text;

namespace EmberTern.Core.Metadata;

/// <summary>
/// Pure DDL emitter. Every output is a fragment of standard Firebird SQL —
/// identifiers are always quoted with <c>"</c>, internal quotes doubled, so
/// names with lowercase letters or reserved words round-trip safely.
/// </summary>
/// <remarks>
/// No I/O, no FbConnection. <c>TableDetailTabViewModel</c> calls these to
/// build <see cref="PendingDdlChange"/> entries; tests cover the shape of the
/// generated SQL directly.
/// </remarks>
public static class DdlGenerator
{
    public static string Quote(string identifier)
    {
        if (string.IsNullOrEmpty(identifier)) return "\"\"";
        return "\"" + identifier.Replace("\"", "\"\"") + "\"";
    }

    /// <summary>
    /// Minimal CREATE TABLE skeleton — single INTEGER NOT NULL PRIMARY KEY column
    /// named ID. The "+ New Table" button emits this; further structure is added
    /// via the Pola sub-tab edit toolbar.
    /// </summary>
    public static string BuildCreateTable(string tableName)
    {
        if (string.IsNullOrWhiteSpace(tableName))
            throw new ArgumentException("Table name is required.", nameof(tableName));

        return $"CREATE TABLE {Quote(tableName.Trim())} (\n  ID INTEGER NOT NULL PRIMARY KEY\n)";
    }

    /// <summary>
    /// <c>ALTER TABLE … DROP …</c>. Caller is responsible for confirming the
    /// destructive intent.
    /// </summary>
    public static string BuildDropField(string tableName, string fieldName)
    {
        if (string.IsNullOrWhiteSpace(tableName))
            throw new ArgumentException("Table name is required.", nameof(tableName));
        if (string.IsNullOrWhiteSpace(fieldName))
            throw new ArgumentException("Field name is required.", nameof(fieldName));

        return $"ALTER TABLE {Quote(tableName.Trim())} DROP {Quote(fieldName.Trim())}";
    }

    /// <summary>
    /// <c>ALTER TABLE … ALTER … POSITION n</c>. Firebird positions are 1-based.
    /// </summary>
    public static string BuildMoveField(string tableName, string fieldName, int oneBasedPosition)
    {
        if (string.IsNullOrWhiteSpace(tableName))
            throw new ArgumentException("Table name is required.", nameof(tableName));
        if (string.IsNullOrWhiteSpace(fieldName))
            throw new ArgumentException("Field name is required.", nameof(fieldName));
        if (oneBasedPosition < 1)
            throw new ArgumentOutOfRangeException(nameof(oneBasedPosition), "Position must be >= 1.");

        return string.Format(
            CultureInfo.InvariantCulture,
            "ALTER TABLE {0} ALTER {1} POSITION {2}",
            Quote(tableName.Trim()), Quote(fieldName.Trim()), oneBasedPosition);
    }

    /// <summary>
    /// Builds the full ADD-FIELD DDL. May return multiple top-level statements
    /// joined by ';' when autoincrement-by-generator is requested — the executor
    /// splits on top-level semicolons (no string literals to worry about for
    /// these statements).
    /// </summary>
    public static string BuildAddField(string tableName, FieldDefinition def)
    {
        if (string.IsNullOrWhiteSpace(tableName))
            throw new ArgumentException("Table name is required.", nameof(tableName));
        if (def is null) throw new ArgumentNullException(nameof(def));
        if (string.IsNullOrWhiteSpace(def.Name))
            throw new ArgumentException("Field name is required.", nameof(def));

        var table = Quote(tableName.Trim());
        var name = Quote(def.Name.Trim());

        var column = new StringBuilder();
        column.Append("ALTER TABLE ").Append(table).Append(" ADD ").Append(name).Append(' ');

        // Computed columns: COMPUTED BY ( … ) takes the place of a regular type
        // declaration — Firebird derives the type from the expression. Domain /
        // BasicType / Default / NotNull are ignored when ComputedExpression is set.
        if (!string.IsNullOrWhiteSpace(def.ComputedExpression))
        {
            column.Append("COMPUTED BY (").Append(def.ComputedExpression.Trim()).Append(')');
        }
        else
        {
            column.Append(FormatTypeOrDomain(def));

            if (!string.IsNullOrWhiteSpace(def.DefaultValue))
            {
                column.Append(" DEFAULT ").Append(def.DefaultValue.Trim());
            }

            if (def.NotNull)
            {
                column.Append(" NOT NULL");
            }

            if (def.AutoIncrement == AutoIncrementMode.Identity)
            {
                // FB3+ syntax — preferred for INTEGER PKs going forward.
                column.Append(" GENERATED BY DEFAULT AS IDENTITY");
            }
        }

        if (!string.IsNullOrWhiteSpace(def.CheckExpression))
        {
            column.Append(" CHECK (").Append(def.CheckExpression.Trim()).Append(')');
        }

        if (def.PrimaryKey)
        {
            column.Append(" PRIMARY KEY");
        }

        var statements = new StringBuilder();
        statements.Append(column);

        // Autoincrement via generator: emits CREATE GENERATOR + CREATE TRIGGER
        // alongside the column add. Identity mode is inline (above) so no extra
        // statements.
        if (def.AutoIncrement == AutoIncrementMode.NewGenerator)
        {
            var genName = (def.GeneratorName ?? string.Empty).Trim();
            if (string.IsNullOrEmpty(genName))
            {
                // Sensible default if the user didn't pick a name.
                genName = "GEN_" + tableName.Trim().ToUpperInvariant() + "_" + def.Name.Trim().ToUpperInvariant();
            }
            statements.Append(';');
            statements.Append('\n');
            statements.Append("CREATE GENERATOR ").Append(Quote(genName));

            statements.Append(';');
            statements.Append('\n');
            statements.Append(BuildAutoIncTrigger(tableName.Trim(), def.Name.Trim(), genName, def.TriggerName));
        }
        else if (def.AutoIncrement == AutoIncrementMode.ExistingGenerator)
        {
            var genName = (def.GeneratorName ?? string.Empty).Trim();
            if (!string.IsNullOrEmpty(genName))
            {
                statements.Append(';');
                statements.Append('\n');
                statements.Append(BuildAutoIncTrigger(tableName.Trim(), def.Name.Trim(), genName, def.TriggerName));
            }
        }

        return statements.ToString();
    }

    /// <summary>
    /// BEFORE INSERT trigger that assigns NEW."FIELD" = GEN_ID("GEN", 1) when
    /// the inserter leaves it NULL. Body is wire-formatted with the FB-standard
    /// SET TERM gymnastics absent — EmberTern uses isql-friendly statement
    /// boundaries (single semicolons; the FbCommand path doesn't need SET TERM).
    /// </summary>
    public static string BuildAutoIncTrigger(string tableName, string fieldName, string generatorName, string? triggerName)
    {
        var trigger = (triggerName ?? string.Empty).Trim();
        if (string.IsNullOrEmpty(trigger))
        {
            trigger = "BI_" + tableName.ToUpperInvariant() + "_" + fieldName.ToUpperInvariant();
        }

        var sb = new StringBuilder();
        sb.Append("CREATE TRIGGER ").Append(Quote(trigger))
          .Append(" FOR ").Append(Quote(tableName))
          .Append(" ACTIVE BEFORE INSERT POSITION 0\n")
          .Append("AS BEGIN\n")
          .Append("  IF (NEW.").Append(Quote(fieldName)).Append(" IS NULL) THEN\n")
          .Append("    NEW.").Append(Quote(fieldName))
          .Append(" = GEN_ID(").Append(Quote(generatorName)).Append(", 1);\n")
          .Append("END");
        return sb.ToString();
    }

    /// <summary>
    /// Renders the type part of an ADD FIELD: either <c>DOMAIN "NAME"</c> or
    /// the basic SQL type with the right modifiers. Falls back to INTEGER if
    /// nothing has been picked yet — keeps the live DDL preview meaningful
    /// even while the user is still filling in the dialog.
    /// </summary>
    public static string FormatTypeOrDomain(FieldDefinition def)
    {
        if (!string.IsNullOrWhiteSpace(def.Domain))
        {
            // Firebird syntax: ADD <name> <DOMAIN_NAME> — no DOMAIN keyword.
            return Quote(def.Domain!.Trim());
        }

        var type = (def.BasicType ?? string.Empty).Trim().ToUpperInvariant();
        if (string.IsNullOrEmpty(type)) type = "INTEGER";

        return type switch
        {
            "CHAR" or "VARCHAR" or "CSTRING"
                => def.Size is { } size ? $"{type}({size.ToString(CultureInfo.InvariantCulture)})" : type,
            "NUMERIC" or "DECIMAL"
                => FormatNumericType(type, def.Precision, def.Scale),
            "BLOB"
                => def.BlobSubType is { } sub
                    ? $"BLOB SUB_TYPE {((int)sub).ToString(CultureInfo.InvariantCulture)}"
                    : "BLOB",
            _ => type,
        };
    }

    private static string FormatNumericType(string type, int? precision, int? scale)
    {
        if (precision is null) return type;
        if (scale is null)
        {
            return $"{type}({precision.Value.ToString(CultureInfo.InvariantCulture)})";
        }
        return $"{type}({precision.Value.ToString(CultureInfo.InvariantCulture)},{scale.Value.ToString(CultureInfo.InvariantCulture)})";
    }

    // ─── Full CREATE TABLE (used by CreateTableDialog) ─────────────────────

    /// <summary>
    /// Renders a complete <c>CREATE TABLE</c> from a <see cref="TableSpec"/>:
    /// persistent or global temporary; column list; inline PRIMARY KEY
    /// constraint when one or more fields are flagged as PK; per-field
    /// autoincrement (CREATE SEQUENCE + CREATE TRIGGER appended after the
    /// CREATE TABLE); optional COMMENT ON TABLE for the description; per-field
    /// COMMENT ON COLUMN for any field that carries one.
    ///
    /// Multiple statements are joined by <c>;</c> — the executor
    /// (<see cref="FirebirdDdlExecutor.SplitStatements"/>) tracks BEGIN/END
    /// nesting so trigger bodies stay intact.
    /// </summary>
    public static string BuildCreateTable(string tableName, TableSpec spec)
    {
        if (string.IsNullOrWhiteSpace(tableName))
            throw new ArgumentException("Table name is required.", nameof(tableName));
        if (spec is null) throw new ArgumentNullException(nameof(spec));

        var table = tableName.Trim();
        var qTable = Quote(table);

        var sb = new StringBuilder();
        sb.Append(spec.Kind switch
        {
            TableKind.TempDeleteRows or TableKind.TempPreserveRows => "CREATE GLOBAL TEMPORARY TABLE ",
            _ => "CREATE TABLE ",
        });
        sb.Append(qTable).Append(" (\n");

        var pkColumns = new List<string>();
        for (int i = 0; i < spec.Fields.Count; i++)
        {
            var field = spec.Fields[i];
            if (string.IsNullOrWhiteSpace(field.Name)) continue;
            if (i > 0 && sb[sb.Length - 1] != '\n') sb.Append('\n');

            sb.Append("  ").Append(Quote(field.Name.Trim())).Append(' ');

            if (!string.IsNullOrWhiteSpace(field.ComputedExpression))
            {
                sb.Append("COMPUTED BY (").Append(field.ComputedExpression.Trim()).Append(')');
            }
            else
            {
                sb.Append(FormatTypeOrDomain(field));

                if (!string.IsNullOrWhiteSpace(field.DefaultValue))
                {
                    sb.Append(" DEFAULT ").Append(field.DefaultValue.Trim());
                }
                if (field.NotNull)
                {
                    sb.Append(" NOT NULL");
                }
                if (field.AutoIncrement == AutoIncrementMode.Identity)
                {
                    sb.Append(" GENERATED BY DEFAULT AS IDENTITY");
                }
            }

            if (!string.IsNullOrWhiteSpace(field.CheckExpression))
            {
                sb.Append(" CHECK (").Append(field.CheckExpression.Trim()).Append(')');
            }

            if (i < spec.Fields.Count - 1 || HasPkColumns(spec)) sb.Append(',');
            sb.Append('\n');

            if (field.PrimaryKey) pkColumns.Add(field.Name.Trim());
        }

        if (pkColumns.Count > 0)
        {
            // Named PK so the constraint is addressable later (drop/rename).
            sb.Append("  CONSTRAINT ").Append(Quote("PK_" + table.ToUpperInvariant()))
              .Append(" PRIMARY KEY (");
            for (int i = 0; i < pkColumns.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(Quote(pkColumns[i]));
            }
            sb.Append(")\n");
        }

        sb.Append(')');

        if (spec.Kind == TableKind.TempDeleteRows)
        {
            sb.Append("\nON COMMIT DELETE ROWS");
        }
        else if (spec.Kind == TableKind.TempPreserveRows)
        {
            sb.Append("\nON COMMIT PRESERVE ROWS");
        }

        // Per-field autoincrement via legacy generator + trigger pattern.
        // Each generates two extra statements after the CREATE TABLE.
        foreach (var field in spec.Fields)
        {
            if (string.IsNullOrWhiteSpace(field.Name)) continue;
            if (field.AutoIncrement != AutoIncrementMode.NewGenerator) continue;

            var fieldName = field.Name.Trim();
            var genName = (field.GeneratorName ?? string.Empty).Trim();
            if (string.IsNullOrEmpty(genName))
            {
                genName = "GEN_" + table.ToUpperInvariant() + "_" + fieldName.ToUpperInvariant();
            }
            var triggerName = (field.TriggerName ?? string.Empty).Trim();
            if (string.IsNullOrEmpty(triggerName))
            {
                triggerName = table.ToUpperInvariant() + "_BI_" + fieldName.ToUpperInvariant();
            }

            sb.Append(";\nCREATE SEQUENCE ").Append(Quote(genName));
            sb.Append(";\nCREATE TRIGGER ").Append(Quote(triggerName))
              .Append(" FOR ").Append(qTable)
              .Append(" ACTIVE BEFORE INSERT POSITION 0\n")
              .Append("AS BEGIN\n")
              .Append("  IF (NEW.").Append(Quote(fieldName)).Append(" IS NULL) THEN\n")
              .Append("    NEW.").Append(Quote(fieldName))
              .Append(" = NEXT VALUE FOR ").Append(Quote(genName)).Append(";\n")
              .Append("END");
        }

        // Optional COMMENT ON TABLE for the table-level description.
        if (!string.IsNullOrWhiteSpace(spec.Description))
        {
            sb.Append(";\n").Append(BuildCommentTable(table, spec.Description));
        }

        // Per-field column comments.
        foreach (var field in spec.Fields)
        {
            if (string.IsNullOrWhiteSpace(field.Name)) continue;
            if (string.IsNullOrWhiteSpace(field.Description)) continue;
            sb.Append(";\n").Append(BuildCommentColumn(table, field.Name.Trim(), field.Description));
        }

        return sb.ToString();
    }

    private static bool HasPkColumns(TableSpec spec)
    {
        foreach (var f in spec.Fields)
        {
            if (f.PrimaryKey) return true;
        }
        return false;
    }

    // ─── ALTER COLUMN — used by the inline editing path on the Pola grid ───

    public static string BuildRenameField(string tableName, string oldName, string newName)
    {
        if (string.IsNullOrWhiteSpace(tableName))
            throw new ArgumentException("Table name is required.", nameof(tableName));
        if (string.IsNullOrWhiteSpace(oldName))
            throw new ArgumentException("Old field name is required.", nameof(oldName));
        if (string.IsNullOrWhiteSpace(newName))
            throw new ArgumentException("New field name is required.", nameof(newName));

        return string.Format(
            CultureInfo.InvariantCulture,
            "ALTER TABLE {0} ALTER {1} TO {2}",
            Quote(tableName.Trim()), Quote(oldName.Trim()), Quote(newName.Trim()));
    }

    /// <summary>Toggles a column's NOT NULL constraint. FB3+ syntax.</summary>
    public static string BuildSetNotNull(string tableName, string fieldName, bool notNull)
    {
        if (string.IsNullOrWhiteSpace(tableName))
            throw new ArgumentException("Table name is required.", nameof(tableName));
        if (string.IsNullOrWhiteSpace(fieldName))
            throw new ArgumentException("Field name is required.", nameof(fieldName));

        return string.Format(
            CultureInfo.InvariantCulture,
            "ALTER TABLE {0} ALTER {1} {2} NOT NULL",
            Quote(tableName.Trim()), Quote(fieldName.Trim()), notNull ? "SET" : "DROP");
    }

    /// <summary>Sets a column default. Pass null/whitespace as
    /// <paramref name="defaultExpression"/> to DROP DEFAULT.</summary>
    public static string BuildSetDefault(string tableName, string fieldName, string? defaultExpression)
    {
        if (string.IsNullOrWhiteSpace(tableName))
            throw new ArgumentException("Table name is required.", nameof(tableName));
        if (string.IsNullOrWhiteSpace(fieldName))
            throw new ArgumentException("Field name is required.", nameof(fieldName));

        if (string.IsNullOrWhiteSpace(defaultExpression))
        {
            return string.Format(
                CultureInfo.InvariantCulture,
                "ALTER TABLE {0} ALTER {1} DROP DEFAULT",
                Quote(tableName.Trim()), Quote(fieldName.Trim()));
        }
        return string.Format(
            CultureInfo.InvariantCulture,
            "ALTER TABLE {0} ALTER {1} SET DEFAULT {2}",
            Quote(tableName.Trim()), Quote(fieldName.Trim()), defaultExpression.Trim());
    }

    /// <summary>Changes a column's type. Caller is responsible for ensuring
    /// the new type is compatible — FB rejects most cross-family conversions
    /// at the engine level (the resulting <c>FbException</c> surfaces as a
    /// Compile failure with the server's own message).</summary>
    public static string BuildAlterType(string tableName, string fieldName, string newType)
    {
        if (string.IsNullOrWhiteSpace(tableName))
            throw new ArgumentException("Table name is required.", nameof(tableName));
        if (string.IsNullOrWhiteSpace(fieldName))
            throw new ArgumentException("Field name is required.", nameof(fieldName));
        if (string.IsNullOrWhiteSpace(newType))
            throw new ArgumentException("New type is required.", nameof(newType));

        return string.Format(
            CultureInfo.InvariantCulture,
            "ALTER TABLE {0} ALTER {1} TYPE {2}",
            Quote(tableName.Trim()), Quote(fieldName.Trim()), newType.Trim());
    }

    /// <summary>Emits <c>COMMENT ON COLUMN "T"."F" IS '...'</c> — single
    /// quotes inside the comment are doubled per SQL string-literal rules.
    /// Pass null/whitespace to clear the comment (<c>IS NULL</c>).</summary>
    public static string BuildCommentColumn(string tableName, string fieldName, string? comment)
    {
        if (string.IsNullOrWhiteSpace(tableName))
            throw new ArgumentException("Table name is required.", nameof(tableName));
        if (string.IsNullOrWhiteSpace(fieldName))
            throw new ArgumentException("Field name is required.", nameof(fieldName));

        var t = Quote(tableName.Trim());
        var f = Quote(fieldName.Trim());
        if (string.IsNullOrWhiteSpace(comment))
        {
            return string.Format(CultureInfo.InvariantCulture,
                "COMMENT ON COLUMN {0}.{1} IS NULL", t, f);
        }
        return string.Format(CultureInfo.InvariantCulture,
            "COMMENT ON COLUMN {0}.{1} IS '{2}'", t, f, EscapeSqlLiteral(comment));
    }

    /// <summary>Like <see cref="BuildCommentColumn"/> but for tables.</summary>
    public static string BuildCommentTable(string tableName, string? comment)
    {
        if (string.IsNullOrWhiteSpace(tableName))
            throw new ArgumentException("Table name is required.", nameof(tableName));

        var t = Quote(tableName.Trim());
        if (string.IsNullOrWhiteSpace(comment))
        {
            return string.Format(CultureInfo.InvariantCulture, "COMMENT ON TABLE {0} IS NULL", t);
        }
        return string.Format(CultureInfo.InvariantCulture, "COMMENT ON TABLE {0} IS '{1}'", t, EscapeSqlLiteral(comment));
    }

    private static string EscapeSqlLiteral(string s) => s.Replace("'", "''");
}
