namespace EmberTern.Core.Metadata;

/// <summary>
/// How the user wants the field to autoincrement. Drives whether the DDL
/// generator emits a GENERATED BY DEFAULT AS IDENTITY clause, reuses an
/// existing generator + trigger, creates a fresh generator + trigger, or
/// emits nothing at all. Identity columns work from Firebird 3 onwards.
/// </summary>
public enum AutoIncrementMode
{
    None,
    Identity,
    ExistingGenerator,
    NewGenerator,
}

/// <summary>
/// What kind of BLOB subtype the user picked. Maps to <c>BLOB SUB_TYPE 0</c>
/// (binary) or <c>BLOB SUB_TYPE 1</c> (text) in the generated DDL.
/// </summary>
public enum BlobSubType
{
    Binary = 0,
    Text = 1,
}

/// <summary>
/// Captures the AddFieldDialog form state in a UI-free shape so
/// <c>DdlGenerator</c> can be exercised by tests without standing up Avalonia.
/// All strings default to empty / null so partial constructions still generate
/// a meaningful DDL string for the live-preview tab.
/// </summary>
public sealed class FieldDefinition
{
    public string Name { get; init; } = string.Empty;

    public bool NotNull { get; init; }
    public bool PrimaryKey { get; init; }

    /// <summary>When non-empty the field is built on a domain — basic-type
    /// fields go through <see cref="BasicType"/> + the per-type modifiers
    /// instead. Domain and BasicType are mutually exclusive: Domain wins.</summary>
    public string? Domain { get; init; }

    /// <summary>Base SQL type (SMALLINT / INTEGER / VARCHAR / NUMERIC / …).
    /// Required when <see cref="Domain"/> is empty.</summary>
    public string? BasicType { get; init; }

    /// <summary>For CHAR/VARCHAR/CSTRING.</summary>
    public int? Size { get; init; }

    /// <summary>For NUMERIC/DECIMAL.</summary>
    public int? Precision { get; init; }

    /// <summary>For NUMERIC/DECIMAL.</summary>
    public int? Scale { get; init; }

    /// <summary>For BLOB.</summary>
    public BlobSubType? BlobSubType { get; init; }

    public string? DefaultValue { get; init; }
    public string? CheckExpression { get; init; }
    public string? ComputedExpression { get; init; }
    public string? Description { get; init; }

    public AutoIncrementMode AutoIncrement { get; init; }
    public string? GeneratorName { get; init; }
    /// <summary>Trigger name for new-generator autoincrement. When empty,
    /// <c>DdlGenerator</c> derives one from the table / field name.</summary>
    public string? TriggerName { get; init; }
}
